### PR TITLE
Implementation of subsequent attachment upload

### PR DESCRIPTION
**Pull request by fedys**
refs gh-231

### CODE REVIEW

**Comment by fedys** [comment]
I haven't found out how to disallow file removing on a server side. I tried to revoke a change permission on given attachments but with no success.

**Comment by TiSiE** [comment]
It's sufficient to just not render the delete button.

FYI:
Attachments inherit the permissions of the application via [Applications\Repository\Event\UpdateFilesPermissionsSubscriber](https://github.com/cross-solution/YAWIK/blob/880247e7d01a01505aae09ce9a0ba6cb29cef647/module/Applications/src/Applications/Repository/Event/UpdateFilesPermissionsSubscriber.php)

**Comment by fedys** [comment]
@TiSiE thanks for info

**Comment by TiSiE** [comment]
What we might have forgot to mention in the issue: At the moment only the applicant should be able to add attachments

**Comment by fedys** [comment]
okay, I am going to implement this condition

**Comment by fedys** [comment]
I noticed I had broken the Core\Form\View\Helper\FormImageUpload. I am fixing it.

**Comment by fedys** [comment]
I will write related unit tests as soon as you find the implementation okay. Please let me know about it.

**Comment by TiSiE** [comment]
@fedys go ahead :smile:

**Comment by fedys** [comment]
Do you want me to write a unit test also for the Applications\Controller\ManageController::detailAction() method?

**Comment by TiSiE** [comment]
@fedys No, ManageController is a mess and will be refactored sooner or later anyway.

**Pull request merged**
