### PR TITLE
Draft & dummy implementation of account removal

### PR DESCRIPTION
**Pull request by fedys**
refs gh-103

### CODE REVIEW

**Comment by fedys** [comment]
Please let me know your thoughts on current dummy implementation.

**Comment by TiSiE** [comment]
I like the concept to push the responsibilities of listing and removing dependent items to the modules.
But maybe an event driven approach would be more flexible and less complex...
Modules could separate the logic of listing and removing items in different listener if they want, and the Auth module does not need to provide an plugin manager, but uses a dedicated event manager, which is created relatively easy, as all necessaries are already implemented: (see https://github.com/cross-solution/YAWIK/issues/234#issuecomment-227384288 /the  last three paragraphs)

And although it is tempting for its simplicity to use a static method as factory, we should use dedicated factory classes, because of SoC principle.

**Comment by fedys** [comment]
@TiSiE 
I made all refactorings you suggested and you were right. It is more simple and flexible. I will avoid using static method factories in the future (although there were also performance reason to use static methods). Let me know if you are happy with the current draft and I will continue with real implementation.

**Comment by TiSiE** [comment]
Looks good, go ahead! :smiley:

**Comment by fedys** [comment]
Let me know if you are happy with the current implementation of related objects listing. If yes, I will supply unit tests and then we can move to the second step, related objects removal.

**Comment by TiSiE** [comment]
Code is alright. @cbleek must review the UI

**Comment by cbleek** [comment]
Am 24.08.2016 um 17:09 schrieb Mathias Gelhausen:
>
> Code is alright. @cbleek <https://github.com/cbleek> must review the UI
>
UI is OK. @fedis please delete the found relations/entities.

Regards,

Carsten

**Pull request merged**
