### PR TITLE
Issue 258

### PR DESCRIPTION
**Pull request by fedys**
This one include multiple changes. See the commit comments.

By the way, I had to change .less file. Unfortunately, I was unable to install lessc plugin for yui-compress (it seems to be an obsolete one), therefore I used the following command for .css generation: `lessc --clean-css yawik.less ../public/css/yawik.css` (resulting css seems to be okay and is even smaller, by using lessc --clean-css="advanced" is even more smaller :))

### CODE REVIEW

**Comment by cbleek** [comment]
I get the notice:

Notice: Use of undefined constant ARRAY_FILTER_USE_KEY - assumed 'ARRAY_FILTER_USE_KEY' in /home/cbleek/Projects/YAWIK/module/Core/src/Core/Form/View/Helper/SummaryForm.php on line 175 

The parameter ARRAY_FILTER_USE_KEY was added in php-5.6.0. We currently have the reqirement php>=5.5.

Can we remove the 5.6 requirement?

**Comment by fedys** [comment]
@cbleek I am sorry, I overlooked that it was added in the PHP 5.6. I thought it was added in the PHP 5.0 :relaxed:

**Comment by cbleek** [comment]
@fedys . looks very good. I'll merge it.

**Comment by fedys** [comment]
@cbleek Great!

**Pull request merged**
