### PR TITLE
implementation of the issue #233

### PR DESCRIPTION
**Pull request by fedys**
refs gh-233

### CODE REVIEW

**Comment by fedys** [comment]
What about summary field? It is discarded during moving to talent pool now.

**Comment by TiSiE** [comment]
@fedys 
Summary field is meant to be used as a kind of cover letter specific to the job. So it has little use in a general CV anyway and can be discarded

**Comment by fedys** [comment]
@TiSiE 
no problem, I just wanted you to know about it :)

**Comment by TiSiE** [comment]
@fedys 
As I quickly glanced over the implementation, I noticed that a lot of code in the moveAction of the ManageController deals with actual copying... which should better be done in a dedicated Unit of Work (Controller Plugin, Repository Decorator or similar) with well defined dependencies. 

Also additionally it would be very nice, if it will be possible to copy many applications at once using the MultiActions in the list view.

**Comment by fedys** [comment]
@TiSiE 

I am absolutely with you, the implementation should be moved out of the Controller. Actually, it is my approach to make a quick & dirty implementation of given task in case I am not sure about all details of functionality. And after you consider the functionality correct, it is time for a refactoring. This approach saves me a lot of time in such cases because I do not have to rework a fine tuned implementation.

1. I am going to move the copying to `\Core\Repository\AbstractRepository::createFromApplication(Application $application) : Cv` method
2. I am going to add the multiple move action

OK?

**Comment by fedys** [comment]
I will supply unit tests tomorrow.

**Pull request merged**
