### PR TITLE
travis and scrutinizer build improvements

### PR DESCRIPTION
**Pull request by kilip**
This pull request will improve travis build:
- completely disable xdebug
- use phpdbg to generate code-coverage
- using travis .steps
- change composer.json **self.version** to **0.33**, to fix external yawik module install error

### CODE REVIEW

**Comment by kilip** [comment]
@TiSiE @cbleek 
Don't know why scrutinizer build is not triggered. Scrutinizer build should be fixed now

**Comment by cbleek** [comment]
I think @TiSiE has removed it in repo settings of "integrations & settings". But he's on holidy. However...

I have a question about composer.lock. You delete it and we add it from time to time. I thought the "composer.lock" would guarantee that a build would always have fixed versions.

What's the disadvantage if the composer.lock is also stored in the repository?

**Comment by kilip** [comment]
@cbleek 
Well actually the disadvantage is we will always have fixed versions. We will don't know what behavior occurs when our library in dependencies, like zend framework is releasing new version. Without storing composer.lock and by the help of travis build we can detect errors when this libraries releasing their new version. We can also use composer options ```--prefer-lowest``` and ```--prefer-latest``` in travis build to detect this errors.

However for a real application we will need that composer.lock file to be sure that library version in our development is same as in production.

For better explanation please read this [article](https://blog.martinhujer.cz/17-tips-for-using-composer-efficiently/) (Tips number 5 to 7)

**Comment by TiSiE** [comment]
I disagree. composer.lock must always be committed.

https://www.engineyard.com/blog/composer-its-all-about-the-lock-file
https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

> Well actually the disadvantage is we will always have fixed versions. 

That's exactly the point of the composer.lock. Everyone uses the __exact same__ versions of every dependency.   

> We will don't know what behavior occurs when our library in dependencies, like zend framework is releasing new version. 

And with composer.lock we could not care less. Because we know, the version that will be installed using the composer.lock is the version _we have tested_ with.

> Without storing composer.lock and by the help of travis build we can detect errors when this libraries releasing their new version. We can also use composer options --prefer-lowest and --prefer-latest in travis build to detect this errors.

That is actually a good idea. Use a dedicated travis job per commit to explicitly run composer update.
This should however allow failure. We can then look at the outcome and when everything works in that build, we can assume that updating the dependencies _in a dedicated feature branch_ will cause eventually not so much work. Once updated and tested __in the development environment__, the branch along with the new `composer.lock` will be merged. 


Apart from that, there are some other advantages of using composer.lock:
* composer install is significant faster than update - because no dependencies needs to be checked.   
* If you work on a feature branch, which requires a new dependency, you need to run composer update.
Then a critical bug is detected, that must be fixed immediately. So, switch branch, composer install to get the dependencies __for this branch__ and fix the bug. Switch back to the feature branch and composer install again. Without composer.lock that would be a hassle (if not impossible).


And regaring the difference between projects and libriaries:
Althoug the composer.lock is completely ignored when installing the library as a dependency for another project, it still needs to be developed. And then, the library will be a project for the developers.

**Comment by kilip** [comment]
@TiSiE 

Actually it depends on the type of project/code. For example I will use Yawik modules for my own website. I can create this website by using [yawik/standard](https://github.com/yawik/standard) as template, then off course I should add composer.lock because I need to be sure that my deps in development same as my production environment and other developers using the same version too.

To me the OpenCFP mentioned in engine yard article is not like```cross-solution/yawik``` repo, in this repo we just build a library to be used later in other zendframework based application. The OpenCFP repo is not a library type application so they need to keep their ```composer.lock``` files.

But I think the more important things is we need to detect the dependencies update, we need to be sure that when we update our dependencies into the newer version we can detect any error. And we can use travis help to detect this update failure. I think we can use travis config like this [zendframework/zend-mail](https://github.com/zendframework/zend-mail/blob/master/.travis.yml) library in our yawik project.

**Comment by TiSiE** [comment]
> But I think the more important things is we need to detect the dependencies update, we need to be sure that when we update our dependencies into the newer version we can detect any error. And we can use travis help to detect this update failure. 

I totally agree to this. It is independent from a committed composer.lock, though. In the travis build used to detect errors on dependent libraries, we can use a `composer update` which ignores the composer.lock. Or we could delete the composer.lock inside the specific travis build prior to installing.

But my point still stands, the composer.lock must be committed.

**Comment by TiSiE** [comment]
This will be merged  with #555

**Pull request closed without merging**
