### PR TITLE
release-0.32.0-RC1 preparation

### PR DESCRIPTION
**Pull request by kilip**
Hello @cbleek @TiSiE 

ATTENTION!
----
Please **do not merge** this pull request into **develop**, we need to create spesific branch like **release-0.32.0-RC1** branch for this pull request

New release command
----
I have prepare the **0.32.0-RC1** in this pull request. I also add a new console command to release Yawik. To use command please create a new file in your local yawik dev:
```php
// path/to/yawik/config/release.local.php
return [
    'release' => [
        /*
         * Change this value to match with your remote
         * configuration that pointing to: git@github.com:cross-solution/YAWIK.git
         * ( use `git remote -v` command to know which remote name)
         */
        'main_remote_name' => 'origin',

        /*
         * If you don't want to keep git clone for yawik/* repository
         * in your local directories just leave this value commented.
         */
        //'subsplit_clone_dir' => sys_get_temp_dir().'/yawik/build',
    ],
];
```

The command  can be executed with:
```sh
$ cd /path/to/yawik
$ bin/console release --message="Release v0.32.0-RC1" v0.32.0-RC1

# use --dry-run command to print git command that will be executed during release process
# no change will be made if using this option
$ bin/console release --message="Release v0.32.0-RC1" v0.32.0-RC1 --dry-run
```
This command will push new tag to ```cross-solution/YAWIK``` and all subsplit repo at ```yawik/*```.

### CODE REVIEW

**Comment by cbleek** [comment]
this sounds good. Who is going to create the branch?

**Comment by kilip** [comment]
@cbleek 
I can't create that branch. I can not push directly into this repository. If you want, add me as github cross-solution member and I will create this branch.

**Comment by kilip** [comment]
@TiSiE 

I am ok with alpha. If you want I can change the ```Core\Module::VERSION``` to alpha1 now

**Comment by kilip** [comment]
@TiSiE I have changed the ```Core\Module::VERSION``` to ```0.32.0-alpha1```. Our ```bin/console release v0.32.0-alpha1``` command will validate this value to be sure that everything is ready for that release.

After releasing this alpha1, we need to change that ```Core\Module::VERSION``` to ```0.32-dev``` in master branch.

**Comment by kilip** [comment]
@cbleek @TiSiE 

I think we can merge this pull request into develop and creating a tags based on develop branch. I have change release command, so it can make a tag from a develop branch:
```sh
$ bin/console release --branch=develop --dry-run v0.32.0-alpha1

# use dry run to test command and show what git command to be executed
$ bin/console release --branch=develop --dry-run v0.32.0-alpha1 --dry-run
```

**Comment by TiSiE** [comment]
> I think we can merge this pull request into develop and creating a tags based on develop branch. I have change release command, so it can make a tag from a develop branch:

What if I want to release in the `release-0.32.0` branch? 
This branch does not exist in either of the yawik/* modules....

It would be cumbersome to create all the branches manually... Must we alter the subsplit command?
Or am I creating more hassle than needed? 
I'd like to have a dedicated release branch so development of upcoming features can continue in the develop branch.

**Comment by kilip** [comment]
> It would be cumbersome to create all the branches manually... Must we alter the subsplit command? Or am I creating more hassle than needed?

We can create this yawik/* branches automatically by using ```bin/console subsplit``` command. Our subsplit command already provide this case with --heads option.

> I'd like to have a dedicated release branch so development of upcoming features can continue in the develop branch.

Yes, we can have those dedicated release branch. In fact I am strongly suggested we create 0.31 branch from master now, to keep archive <=0.31 version.

We are not releasing a stable version yet, so I think it's ok to use just a develop branch. And I think some change in this pull request need to be in develop branch too like what I did for ```module/*/composer.json``` file. We can create this dedicated branch later.

If you still want to create this branch the most commonly used name for this branch is like 0.32 so it can be automatically recognizable by composer/packagist . Here's what to do if you want to create those branch.
1.  create and push branch 0.32
2.  merge this pull request into that branch
3.  pull again from your remote into local dev
4.  use our ```subsplit``` command to create this branch:
```sh
$ cd path/to/yawik
$ bin/console subsplit --heads=0.32 
```
5. Create a tags by using bin/console release as I described above:
```sh
$ bin/console release 0.32.0-alpha1
```

**Comment by TiSiE** [comment]
No, there's no need to keep release branches once the release is done.
The release commit will be tagged, the master branch moved to this release.

But while releasing (I mean -alpha, -beta, -RC releases) these should be in a dedicated branch.
I wanted to know, if I have to create the branch manually in the yawik/* repos - which you have answered. (--heads option).

>And I think some change in this pull request need to be in develop branch too like what I did for module/*/composer.json file.

Merging releases in develop branch can be done anytime. But we should not merge develop branch in release branches. 

So what I want to do is:

1. Merge this pull request in `release-0.32.0`
2. Use subsplit command to create the branch in the yawik/* repositories.
3. release a `0.32.0-alpha1` in the `release-0.32.0` branch
4. Merge the tagged commit in develop (with --no-ff)

Packagist should recognize the tag.

**Comment by kilip** [comment]
if you create this release branch and then delete it again, you have to remember that you need to delete this release branch in yawik/* repo too.

> But while releasing (I mean -alpha, -beta, -RC releases) these should be in a dedicated branch. I wanted to know, if I have to create the branch manually in the yawik/* repos - which you have answered. (--heads option).

I still can't understand why you want to use a release branch. A develop branch should be enough for unstable version. We can keep continue working in develop without this release branch.

**Comment by TiSiE** [comment]
> I still can't understand why you want to use a release branch. A develop branch should be enough for unstable version. We can keep continue working in develop without this release branch

Once a release is started, there should no additional features be added to it. Using only the `develop` branch would mean to defer the merging of new features until the release is done.

Having a dedicated release branch allows to focus on feature hardening and last minute bug fixes on the release and developing new features (and continue to integrate them in the develop branch) at the same time.

I don't know how I could articulate this in a more comprehensible way. Let me try:

The current stable version of YAWIK is `0.31.1`
The `develop` branch is `0.32-dev`
We decide now is the time to prepare the 0.32.0 release.
We create a release branch, which become `0.32-dev`, releasing -alpha, -beta and -RC versions along the way - no new features will be added.
The develop branch is `0.33-dev` from that moment on. New features can be added, which then will go into the `0.33.0` release.

**Comment by kilip** [comment]
@TiSie finally I understand why you want this branch.

Just do what you want to do as you mentioned earlier.

**Pull request merged**
