### PR TITLE
Release 0.32.0

### PR DESCRIPTION
**Pull request by TiSiE**

### CODE REVIEW

**Comment by TiSiE** [comment]
Still, there are some things to do.

* The travis builds for sub-modules currently fail, because \Yawik\Composer\RequireFilesPermissionInterface cannot be found.   
That's because yawik/composer-plugin is not installed.

* When yawik/composer-plugin is installed, the travis builds still fails, because the ModuleManager tries to load the module "Cv" - which is not installed in submodule builds.

**Comment by kilip** [comment]
> Still, there are some things to do.
> 
> * The travis builds for sub-modules currently fail, because \Yawik\Composer\RequireFilesPermissionInterface cannot be found.
>   That's because yawik/composer-plugin is not installed.
> * When yawik/composer-plugin is installed, the travis builds still fails, because the ModuleManager tries to load the module "Cv" - which is not installed in submodule builds.

@TiSiE in submodule build you can add ```yawik/application-pack``` for full yawik main-module or ```yawik/core```, ```yawik/cv``` to just add needed module.

**Comment by TiSiE** [comment]
>  in submodule build you can add `yawik/application-pack` for full yawik main-module, or `yawik/core`, `yawik/cv` to just add needed module.
> 

The real issue here is, even if the Cv module is neither needed nor installed, the ModuleManager still tries to load it. So it must be listed in a application config file somewhere.

**Comment by kilip** [comment]
@TiSiE do you know how to reproduce that issue?

**Comment by TiSiE** [comment]
@kilip don't worry, it was my fault. The particular submodule depends indeed on yawik/cv

**Pull request merged**
