### PR TITLE
ZF3 Fixes

### PR DESCRIPTION
**Pull request by kilip**
This pull request also contain fix for #398 issue

### CODE REVIEW

**Comment by cbleek** [comment]
@TiSiE please check this

**Comment by cbleek** [comment]
@TiSiE whats the status?

**Comment by TiSiE** [comment]
This PR does not fix #398 as stated.

**Comment by TiSiE** [comment]
We have merged this request to be able to continue working on ZF3 integration.

@kilip  Issue #398 still needs to be fixed. But in a new PR.

**Pull request merged**
