### PR TITLE
Tracy has been set as a default error/exception logger #416

### PR DESCRIPTION
**Pull request by fedys**
ErrorLogger has been completely removed with its related classes/configs
Tracy also includes an Exception markup as an attachment

### CODE REVIEW

**Comment by fedys** [comment]
I tested the following scenarios:

- production HTTP: notice, exception & fatal
- production CLI: notice, exception & fatal
- development HTTP: notice, exception & fatal
- development CLI: notice, exception & fatal

I am not 100% sure about removed classes/configuration. I assume they are all related with the old ErrorLogger. Please check the removals carefully.

Consider the following idea. Create a single "System" logger which would replace multiple 'Core/Log' & 'Log/Core/Mail' loggers. This logger would have several writers attached. These writer would log messages into different locations depending of a message severity. For example, all messages would be written into yawik.log, severity above 'error' would be written into error.log and also **send via Tracy email**.

**Comment by TiSiE** [comment]
I don't grasp why we would need such a "System Logger", when tracy DOES log automatically into specific files in its log directory (as I understand). Don't get me wrong, such a Logger would be fancy indeed..

**Comment by fedys** [comment]
@TiSiE  See the following example where the System logger could be used  to log to file and send email.
https://github.com/cross-solution/YAWIK/blob/dee413c298933038a53a962ff52b996c3caa5a9f/module/Auth/src/Auth/Controller/RegisterConfirmationController.php#L53

**Comment by fedys** [comment]
@TiSiE In other words, the System logger could be used in cases when something unexpected happens but you do not want to let the application crash.

**Comment by TiSiE** [comment]
@fedys I see. We should keep that idea around!

**Pull request merged**
